general.import = [
    "./kanagawa-dragon.toml"
]

[window]
opacity = 0.9
padding = {x = 10, y = 10}
decorations = "None"

#[colors.primary]
#background = '#181818'

[font]
normal = { family = "VictorMono NF", style = "Regular" } 
size = 14
