[colors.primary]
foreground = "#5c6a72"
background = "#fdf6e3"

[colors.cursor]
text = "#fdf6e3"
cursor = "#5c6a72"

[colors.selection]
text = "#5c6a72"
background = "#efe9d5"

[colors.normal]
black = "#5c6a72"
red = "#f85552"
green = "#8da101"
yellow = "#dfa000"
blue = "#3a94c5"
magenta = "#df69ba"
cyan = "#35a77c"
white = "#939f91"

[colors.bright]
black = "#5c6a72"
red = "#f85552"
green = "#8da101"
yellow = "#dfa000"
blue = "#3a94c5"
magenta = "#df69ba"
cyan = "#35a77c"
white = "#f4f0d9"
